name: SWEN AIOps GitOps Pipeline

on:
  push:
    branches:
      - main
      - 'ai-recommendation/**'
  pull_request:
    branches:
      - main

env:
  TF_VERSION: '1.5.0'
  TF_ROOT: './infra/envs/prod'

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform Init
        run: |
          cd ${{ env.TF_ROOT }}
          terraform init -backend=false
      
      - name: Terraform Validate
        run: |
          cd ${{ env.TF_ROOT }}
          terraform validate
          terraform fmt -check -recursive

  policy-check:
    name: Policy Evaluation
    runs-on: ubuntu-latest
    outputs:
      auto_approve: ${{ steps.policy.outputs.auto_approve }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Policy Check
        id: policy
        run: |
          echo "Checking AI recommendation policy..."
          
          # Check if this is an AI recommendation branch
          if [[ "${{ github.ref }}" =~ refs/heads/ai-recommendation/.* ]]; then
            echo "AI recommendation branch detected"
            
            # Check for metadata file
            if [ -f "${{ env.TF_ROOT }}/ai-metadata.json" ]; then
              python3 ops/policy_gate.py
              POLICY_EXIT_CODE=$?
              
              if [ $POLICY_EXIT_CODE -eq 0 ]; then
                echo "AUTO-APPROVE: Change meets policy criteria"
                echo "auto_approve=true" >> $GITHUB_OUTPUT
              else
                echo "MANUAL-APPROVAL: Change requires human review"
                echo "auto_approve=false" >> $GITHUB_OUTPUT
              fi
            else
              echo "No metadata found, defaulting to manual approval"
              echo "auto_approve=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "Regular branch, proceeding with standard workflow"
            echo "auto_approve=false" >> $GITHUB_OUTPUT
          fi

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform Init
        run: |
          cd ${{ env.TF_ROOT }}
          terraform init
      
      - name: Check AWS Credentials
        id: check_creds
        run: |
          if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "has_credentials=true" >> $GITHUB_OUTPUT
            echo "AWS credentials found"
          else
            echo "has_credentials=false" >> $GITHUB_OUTPUT
            echo "No AWS credentials found - running validation only"
          fi
      
      - name: Terraform Plan (with credentials)
        if: steps.check_creds.outputs.has_credentials == 'true'
        run: |
          cd ${{ env.TF_ROOT }}
          terraform plan -out=tfplan
          terraform show -json tfplan > plan.json
          echo "=== Terraform Plan Summary ==="
          terraform show tfplan
      
      - name: Terraform Validate Only (no credentials)
        if: steps.check_creds.outputs.has_credentials == 'false'
        run: |
          cd ${{ env.TF_ROOT }}
          echo "=== Terraform Validation Only (No Credentials) ==="
          terraform validate
          echo "✅ Terraform configuration is valid"
          echo "ℹ️  Skipping plan due to missing AWS credentials"
          echo "ℹ️  This is expected for test environments"
      
      - name: Upload Plan Artifacts
        if: steps.check_creds.outputs.has_credentials == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            ${{ env.TF_ROOT }}/tfplan
            ${{ env.TF_ROOT }}/plan.json

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [plan, policy-check]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/ai-recommendation/')
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Check AWS Credentials
        id: check_creds
        run: |
          if [ -n "$AWS_ACCESS_KEY_ID" ] && [ -n "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "has_credentials=true" >> $GITHUB_OUTPUT
            echo "AWS credentials found"
          else
            echo "has_credentials=false" >> $GITHUB_OUTPUT
            echo "No AWS credentials found - skipping apply"
          fi
      
      - name: Download Plan Artifacts
        if: steps.check_creds.outputs.has_credentials == 'true'
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_ROOT }}
      
      - name: Terraform Init
        if: steps.check_creds.outputs.has_credentials == 'true'
        run: |
          cd ${{ env.TF_ROOT }}
          terraform init
      
      - name: Terraform Apply
        if: steps.check_creds.outputs.has_credentials == 'true'
        run: |
          cd ${{ env.TF_ROOT }}
          if [ "${{ needs.policy-check.outputs.auto_approve }}" == "true" ]; then
            echo "Auto-applying approved AI recommendation..."
            terraform apply -auto-approve tfplan
          else
            echo "Manual approval required"
            terraform apply tfplan
          fi
      
      - name: Terraform Output
        if: steps.check_creds.outputs.has_credentials == 'true'
        run: |
          cd ${{ env.TF_ROOT }}
          terraform output -json > outputs.json
      
      - name: Upload Outputs
        if: steps.check_creds.outputs.has_credentials == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: ${{ env.TF_ROOT }}/outputs.json
      
      - name: Skip Apply (No Credentials)
        if: steps.check_creds.outputs.has_credentials == 'false'
        run: |
          echo "ℹ️  Skipping Terraform apply due to missing AWS credentials"
          echo "ℹ️  This is expected for test environments"
          echo "ℹ️  Configuration validation passed successfully"
          echo "✅ AI recommendation would be applied in production environment"

  notify:
    name: Notify Dashboard
    runs-on: ubuntu-latest
    needs: [apply]
    if: always()
    steps:
      - name: Notify Dashboard
        run: |
          echo "Deployment completed for branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          
          # Determine status based on whether credentials were available
          if [ "${{ needs.apply.result }}" == "success" ]; then
            STATUS="success"
            echo "✅ Pipeline completed successfully"
          else
            STATUS="skipped"
            echo "ℹ️  Pipeline completed (validation only - no credentials)"
          fi
          
          # Send notification to dashboard API (if available)
          if [ -n "${{ secrets.DASHBOARD_WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.DASHBOARD_WEBHOOK_URL }}/api/deployments" \
              -H "Content-Type: application/json" \
              -d "{
                \"branch\": \"${{ github.ref_name }}\",
                \"commit\": \"${{ github.sha }}\",
                \"status\": \"$STATUS\",
                \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
                \"auto_approved\": ${{ needs.policy-check.outputs.auto_approve }}
              }"
          else
            echo "ℹ️  No dashboard webhook URL configured"
          fi
